application: matomotter
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /sample1\.py
  script: sample1.py

- url: /sample2\.py
  script: sample2.py
