application: matomotter
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css/

- url: /font
  static_dir: font/

- url: /img
  static_dir: img/

- url: /templates
  static_dir: templates/

- url: /
  script: main.py